apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: first-cert
  namespace: sandbox
spec:
  commonName: first-cert.local
  dnsNames:
  - '*.example.com'
  - example.com
  - example.org
  secretName: first-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io